
name: MPS-QA_CI

on:
  push:
    branches:
      - master
      - 'maintenance/*'
  pull_request:
  workflow_dispatch:
    inputs:
      publish:
        description: Whether to publish the build result to Maven repositories
        type: boolean
        default: false
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.MPS_CI_BUILD_BOT_ACCESS_TOKEN }}

jobs:
  build_mps_qa_packages:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v4

    - name: Setup headless environment
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
       
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build MPS-QA and migrate
      run: |
          ./gradlew build migrate rerunMigrations \
            -Partifacts.itemis.cloud.user=${{secrets.ARTIFACTS_ITEMIS_CLOUD_USER}} \
            -Partifacts.itemis.cloud.pw=${{secrets.ARTIFACTS_ITEMIS_CLOUD_PW}}

    - name: Check for no dirty files after build and migration
      run: |
        if [[ -n $(git status --porcelain | head --lines=1) ]]
        then
          echo "Dirty files detected after build/migration, run './gradlew migrate' and/or update .gitignore to fix:"
          git status
          exit 1
        fi

    - name: Publish

      # Only publish on push (to maintenance or master) or when explicitly requested
      if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish == 'true') }}

      run: |
        ./gradlew publish -x build_allInOne_package \
          -Partifacts.itemis.cloud.user=${{secrets.ARTIFACTS_ITEMIS_CLOUD_USER}} \
          -Partifacts.itemis.cloud.pw=${{secrets.ARTIFACTS_ITEMIS_CLOUD_PW}}

    - name: Archive distribution
      uses: actions/upload-artifact@v4
      with:
        name: org.mpsqa.allInOne
        path: build/artifacts/org.mpsqa.allInOne/
